### ISSUE TITLE
Make a general base fragment for the fragments with loading layout.

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/WallUP#16]
Currently, PopularTagsFragment, BrowseFragment, SearchFragment and WallpaperDetail Fragment all have the same code to show loading layout in their viewmodels. We need to create a new base fragment with a viewmodel which would be only responsible to show the loading layout. We can then inherit this fragment into other fragments which require to show the loading layout.

**Comment by dhruvnagarajan** [comment]
Hey I got this, I'll take this from here. You can assign it to me.

**Comment by dhruvnagarajan** [comment]
Missing drawable 'ic_settings_theme'

**Comment by dhruvnagarajan** [comment]
About section of the app needs some language refinement. What makes this app unique is not clear. Second bullet point has grammatical errors.

**Comment by dhruvnagarajan** [comment]
Can we also raise a ticket for about section fixes?

**Comment by dhruvnagarajan** [comment]
Need to crop wallpaper while setting it. It sets the wallpaper from top left pixel onto the screen; either we should automatically do center crop or allow user to crop.

**Comment by justdvnsh** [comment]
@dhruvnagarajan You're killing it. Thank you so much for your efforts. I'll assign this issue to you. And please star the repo if possible. It really helps a lot.

Also, please make a new issue for all of those you mentioned and tag me. I'll assign them as well. Thanks .

Also, do checkout my other project at https://github.com/justdvnsh/AnimeClassroom 
you'll find suitable issues there as well. And please do a qa check for that app as well if possible and raise mew issue if found. Thank again and happy coding

**Comment by justdvnsh** [comment]
> Need to crop wallpaper while setting it. It sets the wallpaper from top left pixel onto the screen; either we should automatically do center crop or allow user to crop.

As for this issue, I am using my own Library https://github.com/justdvnsh/twoDScrollableZoomableLayout for this and that is not ready for production yet. so yeah you may be encountering bugs due to that library. issues are available there as well, if you wish to solve them. Thanks again for your efforts

**Comment by dhruvnagarajan** [comment]
> Missing drawable 'ic_settings_theme'

I've added a generic settings icon found on material website.
