### ISSUE TITLE
Implement a splash screen with lottie animation

### ISSUE THREAD

**Issue by justdvnsh** [justdvnsh/WallUP#5]
We need to add a splash screen with lottie animation to show the app logo and name.

**Comment by AdiAr11** [comment]
can i work on this issue? thank you

**Comment by justdvnsh** [comment]
Hi @AdiAr11 Sure. That would be great. Please add the screen similar to the AnimeClassroom project's splash screen. Thanks and please star the repo if possible.

**Comment by AdiAr11** [comment]
thank you for the opportunity. I've starred the repo so that it reaches more people.

**Comment by justdvnsh** [comment]
Merged with #22
